import { type AER, type Action, type Mutation, parseAER } from "@aer/core";
import { styles } from "./styles.js";

export function renderHTML(input: AER): string {
  const aer = parseAER(input);
  const title = `AER Viewer - ${aer.run.id}`;
  const optionalSections = [
    renderFilesTouched(aer),
    renderVerification(aer),
    renderClaims(aer),
    renderMutations(aer),
  ]
    .filter(Boolean)
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)}</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<style>${styles}</style>
</head>
<body>
<header class="topbar">
  <div class="logo"><span class="dot">●</span>AER</div>
  <div class="crumb">${escapeHtml(aer.run.source)} / ${escapeHtml(aer.run.mode)}</div>
  <div class="spacer"></div>
  <div class="runid">${escapeHtml(aer.run.id)}</div>
</header>
<main class="container">
  ${renderSummary(aer)}
  ${renderPhases(aer)}
  ${optionalSections}
  ${renderCosts(aer)}
  ${renderRaw(aer)}
  <footer class="footer">Generated by AER v${escapeHtml(aer.version)}. Static, local, deterministic.</footer>
</main>
<script type="application/json" id="aer-data">${escapeScriptJson(aer)}</script>
</body>
</html>`;
}

export function renderSummary(aer: AER): string {
  const outcomeClass = aer.run.outcome === "completed" ? "ok" : "attn";
  return `<section class="hero">
  <div class="eyebrow"><span class="dot"></span>${escapeHtml(aer.run.outcome)} · ${escapeHtml(aer.run.source)}</div>
  <h1>${escapeHtml(runTitle(aer))}</h1>
  <p class="goal">${escapeHtml(aer.run.goal)}</p>
  ${renderNotice(aer)}
  <div class="metrics">
    ${metric("Duration", formatDuration(aer.costs.durationMs))}
    ${metric("Actions", aer.actions.length.toString())}
    ${metric("Tool calls", aer.costs.toolCalls.toString())}
    ${metric("Mutations", aer.mutations.length.toString(), aer.mutations.length > 0 ? "attn" : "")}
    ${metric("Outcome", aer.run.outcome, outcomeClass)}
  </div>
</section>`;
}

export function renderPhases(aer: AER): string {
  const actionsById = new Map(aer.actions.map((action) => [action.id, action]));
  return `<section class="section" id="phases">
  <header><h2>Phases</h2><span class="count">${aer.phases.length}</span></header>
  ${aer.phases
    .map((phase) => {
      const actions = phase.actionIds
        .map((id) => actionsById.get(id))
        .filter((action): action is Action => action !== undefined);
      return `<article class="phase">
    <div class="meta">
      <span class="num">Phase ${phase.index}</span>
      <span class="time">${formatTime(phase.startedAt)}-${formatTime(phase.endedAt)}</span>
      <div class="dur">${formatDuration(phase.durationMs)}</div>
    </div>
    <div>
      <div class="name">${escapeHtml(phase.name)}</div>
      ${phase.why ? `<div class="why">${escapeHtml(phase.why)}</div>` : ""}
      <div class="actions">${renderActionList(actions)}</div>
    </div>
  </article>`;
    })
    .join("\n")}
</section>`;
}

export function renderFilesTouched(aer: AER): string {
  if (aer.filesTouched.length === 0) return "";
  return `<section class="section" id="files-touched">
  <header><h2>Files Touched</h2><span class="count">${aer.filesTouched.length}</span></header>
  ${aer.filesTouched
    .map(
      (file) => `<div class="file-row">
    <div class="path" title="${escapeAttr(file.path)}">${escapeHtml(file.path)}</div>
    <span class="badge ${statusClass(file.status)}">${escapeHtml(file.status)}</span>
    <span class="stats"><span class="add">+${file.linesAdded}</span> <span class="rem">-${file.linesRemoved}</span></span>
    <span class="ref">${escapeHtml(file.mutationIds.join(", "))}</span>
  </div>`,
    )
    .join("\n")}
</section>`;
}

export function renderVerification(aer: AER): string {
  if (aer.verification.length === 0) return "";
  return `<section class="section" id="verification">
  <header><h2>Verification</h2><span class="count">${aer.verification.length}</span></header>
  ${aer.verification
    .map(
      (check) => `<div class="verify-row ${check.outcome === "passed" ? "ok" : "fail"}">
    <div class="icon">${check.outcome === "passed" ? "✓" : "!"}</div>
    <div>
      <div class="label">${escapeHtml(check.command)}</div>
      ${check.detail ? `<div class="detail">${escapeHtml(check.detail)}</div>` : ""}
    </div>
    <span class="ref">${escapeHtml(check.finalActionId)}</span>
  </div>`,
    )
    .join("\n")}
</section>`;
}

export function renderClaims(aer: AER): string {
  if (aer.claims.length === 0) return "";
  return `<section class="section" id="claims">
  <header><h2>Claims</h2><span class="count">${aer.claims.length}</span></header>
  ${aer.claims
    .map(
      (claim) => `<article class="claim">
    <div>${escapeHtml(claim.text)}</div>
    <div class="detail">Evidence: ${escapeHtml(claim.evidence.join(", ") || "none")}</div>
    ${claim.flags.length > 0 ? `<div class="flags">${escapeHtml(claim.flags.join(", "))}</div>` : ""}
  </article>`,
    )
    .join("\n")}
</section>`;
}

export function renderMutations(aer: AER): string {
  if (aer.mutations.length === 0) return "";
  const open = aer.mutations.length <= 3 ? " open" : "";
  return `<section class="section" id="mutations">
  <header><h2>Mutations</h2><span class="count">${aer.mutations.length}</span></header>
  <details${open}>
    <summary>${aer.mutations.length} mutation${aer.mutations.length === 1 ? "" : "s"} · click to inspect diffs</summary>
    ${aer.mutations.map(renderMutation).join("\n")}
  </details>
</section>`;
}

export function renderCosts(aer: AER): string {
  return `<section class="section" id="costs">
  <header><h2>Costs</h2></header>
  <div class="raw-block">${escapeHtml(
    JSON.stringify(
      {
        durationMs: aer.costs.durationMs,
        toolCalls: aer.costs.toolCalls,
        mutations: aer.costs.mutations,
        errors: aer.costs.errors,
        retries: aer.costs.retries,
        tokens: aer.costs.tokens,
        searchBudget: aer.costs.searchBudget,
        toolCallBreakdown: aer.costs.toolCallBreakdown,
      },
      null,
      2,
    ),
  )}</div>
</section>`;
}

export function renderRaw(aer: AER): string {
  return `<section class="section" id="raw">
  <header><h2>Raw</h2></header>
  <details>
    <summary>Source metadata</summary>
    <pre class="raw-block">${escapeHtml(JSON.stringify(aer.raw, null, 2))}</pre>
  </details>
</section>`;
}

function renderMutation(mutation: Mutation): string {
  return `<article class="mut">
  <div class="mut-head">
    <span class="badge ${escapeAttr(mutation.kind)}">${escapeHtml(mutation.kind)}</span>
    <span class="path" title="${escapeAttr(mutation.target)}">${escapeHtml(mutation.target)}</span>
    <span class="ref">${escapeHtml(mutation.actionId)} / ${escapeHtml(mutation.id)}</span>
  </div>
  <div class="mut-meta">
    ${mutation.beforeHash ? `<span><span class="k">before</span><span class="v">${shortHash(mutation.beforeHash)}</span></span>` : ""}
    ${mutation.afterHash ? `<span><span class="k">after</span><span class="v">${shortHash(mutation.afterHash)}</span></span>` : ""}
    ${mutation.diffStats ? `<span><span class="k">diff</span><span class="v">+${mutation.diffStats.added} -${mutation.diffStats.removed}</span></span>` : ""}
    <span><span class="k">gate</span><span class="v">${mutation.gateFired ? "yes" : "no"}</span></span>
  </div>
  ${mutation.diff ? `<details class="diff-wrap"><summary>Show diff</summary><pre class="diff">${renderDiff(mutation.diff)}</pre></details>` : ""}
</article>`;
}

function renderActionList(actions: Action[]): string {
  const visible = actions.slice(0, 24).map(renderAction).join("\n");
  if (actions.length <= 24) return visible;
  return `${visible}<details><summary>${actions.length - 24} more actions</summary>${actions
    .slice(24)
    .map(renderAction)
    .join("\n")}</details>`;
}

function renderAction(action: Action): string {
  const classes = ["action"];
  if (action.mutates) classes.push("attn");
  if (action.errored) classes.push("fail");
  const label = action.target ? `${action.toolName}: ${action.target}` : action.toolName;
  return `<span class="${classes.join(" ")}" title="${escapeAttr(action.inputSummary)}">${escapeHtml(label)}<span class="ix">${escapeHtml(action.id)}</span></span>`;
}

function renderDiff(diff: string): string {
  return diff
    .split("\n")
    .map((line) => {
      const cls =
        line.startsWith("+") && !line.startsWith("+++")
          ? "add"
          : line.startsWith("-") && !line.startsWith("---")
            ? "rem"
            : "ctx";
      return `<span class="${cls}">${escapeHtml(line)}</span>`;
    })
    .join("\n");
}

function renderNotice(aer: AER): string {
  if (aer.run.mode === "scheduled") {
    return `<div class="notice"><b>Scheduled run</b><span class="sep">/</span>${escapeHtml(aer.run.trigger ?? "autonomous execution")}</div>`;
  }
  if (aer.costs.errors > 0) {
    return `<div class="notice"><b>${aer.costs.errors} error${aer.costs.errors === 1 ? "" : "s"}</b><span class="sep">/</span>review errored actions before trusting output</div>`;
  }
  return `<div class="notice ok"><b>Deterministic record</b><span class="sep">/</span>no network or LLM enrichment required</div>`;
}

function metric(label: string, value: string, className = ""): string {
  return `<div class="metric"><div class="label">${escapeHtml(label)}</div><div class="value ${className}">${escapeHtml(value)}</div></div>`;
}

function runTitle(aer: AER): string {
  return aer.run.trigger ?? (aer.run.goal.slice(0, 96) || aer.run.id);
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  const seconds = Math.round(ms / 1000);
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  const remainder = seconds % 60;
  return `${minutes}m ${remainder}s`;
}

function formatTime(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toISOString().slice(11, 16);
}

function statusClass(status: string): string {
  if (status === "modified") return "mod";
  return status;
}

function shortHash(hash: string): string {
  return escapeHtml(hash.slice(0, 12));
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeAttr(value: string): string {
  return escapeHtml(value).replace(/'/g, "&#39;");
}

function escapeScriptJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}
